language: java
jdk: oraclejdk11

cache:
  directories:
  - $HOME/.m2

services:
  - docker  
env:
  - DOCKER_IMAGE=ahmadshams/cmm:openjdk_test
  
jobs:
  include:
    - stage: "Build, Test, Deploy"
      script:
      - cd $TRAVIS_BUILD_DIR/adder
      - mvn package
      - cd $TRAVIS_BUILD_DIR
      - ./build_docker.sh
    - stage: Test Docker
      install: skip
      script: 
      - docker run -it $DOCKER_IMAGE bash -c "java -cp /usr/src/myapp/adder-1.0.0.jar  com.dzone.albanoj2.maven.java.App 21 23"
  

    

