language: java
jdk: oraclejdk11

cache:
  directories:
  - $HOME/.m2

services:
  - docker  


jobs:
  include:
    - stage: build docker image
      script:
      - cd adder; mvn package
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - cd ..; docker build -t ahmadshams/cmm:openjdk_test .
  

    

