language: java
jdk: oraclejdk11

cache:
  directories:
  - $HOME/.m2

services:
  - docker  

script: cd adder; mvn package

deploy:
  - provider: script
    script: ./build_docker.sh 
    on:
      branch: master  

    

