language: java
jdk: oraclejdk11

cache:
  directories:
  - $HOME/.m2
  

script:
  - cd adder; mvn package
 

deploy:
  provider: bintray
  skip_cleanup: true
  file: target/adder-1.0.0.jar
  user: $BINTRAY_USER
  key: $BINTRAY_API_KEY
  on:
    branch: master