language: java
jdk: oraclejdk11

cache:
  directories:
  - $HOME/.m2

services:
  - docker  

jobs:
  include:
    - stage: "Build Java"
      script: cd adder; mvn package
    - stage: "Build Docker"
      script: ./build_docker.sh

    

