language: java
jdk: oraclejdk11

cache:
  directories:
  - $HOME/.m2
  
env:
- BINTRAY_API_KEY=1a661413f1492eee3eca7bdd633cc90491f9f1f0
 
script:
  - cd adder; mvn package
 

deploy:
  -
    on:
      branch: master
    provider: bintray
    skip_cleanup: true
    file: target/adder-1.0.0.jar
    user: ahmad-shams
    key: $BINTRAY_API_KEY